### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by hippyau** [avakar/limecc#2]
Hey :)

Trying to try this out... and not winning at all.   

```
11:13:56 (py37-venv) hip@hip-Precision-5530 consolex ±|master ✗|→ limecc calc.y 
Traceback (most recent call last):
  File "/mnt/1c1a7062-9c29-4c72-8632-c00dff98af57/home/hip/dev/limecc/py37-venv/bin/limecc", line 11, in <module>
    load_entry_point('limecc==0.2', 'console_scripts', 'limecc')()
  File "/mnt/1c1a7062-9c29-4c72-8632-c00dff98af57/home/hip/dev/limecc/py37-venv/lib/python3.7/site-packages/limecc/__main__.py", line 47, in _main
    g = parse_lime_grammar(input, filename=fname)
  File "/mnt/1c1a7062-9c29-4c72-8632-c00dff98af57/home/hip/dev/limecc/py37-venv/lib/python3.7/site-packages/limecc/lime_grammar.py", line 431, in parse_lime_grammar
    return p.parse(toks, extract_value=_extract)
  File "/mnt/1c1a7062-9c29-4c72-8632-c00dff98af57/home/hip/dev/limecc/py37-venv/lib/python3.7/site-packages/limecc/lime_grammar.py", line 101, in parse
    return self._parser.parse(*args, context=self, **kw)
  File "/mnt/1c1a7062-9c29-4c72-8632-c00dff98af57/home/hip/dev/limecc/py37-venv/lib/python3.7/site-packages/limecc/lrparser.py", line 483, in parse
    new_ast = reducer(action, context)
  File "/mnt/1c1a7062-9c29-4c72-8632-c00dff98af57/home/hip/dev/limecc/py37-venv/lib/python3.7/site-packages/limecc/lrparser.py", line 416, in default_reducer
    return rule.action(ctx, *args)
TypeError: 'NoneType' object is not callable
```

Any ideas?

**Comment by hippyau** [comment]
Okay, switched to `temp` branch and having some success...

```
11:45:57 (.py37-venv) hip@hip-Precision-5530 consolex ±|temp ✗|→ limecc calc.yll 
Traceback (most recent call last):
  File "/mnt/1c1a7062-9c29-4c72-8632-c00dff98af57/home/hip/dev/limecc/.py37-venv/bin/limecc", line 11, in <module>
    load_entry_point('limecc==0.2', 'console_scripts', 'limecc')()
  File "/mnt/1c1a7062-9c29-4c72-8632-c00dff98af57/home/hip/dev/limecc/.py37-venv/lib/python3.7/site-packages/limecc/__main__.py", line 97, in _main
    fout.write(lime_cpp(p))
  File "/mnt/1c1a7062-9c29-4c72-8632-c00dff98af57/home/hip/dev/limecc/.py37-venv/lib/python3.7/site-packages/limecc/lime_cpp.py", line 527, in lime_cpp
    or idx_counts.keys()[0] != annot_indexes[sym_annot[rule.left]]):
TypeError: 'dict_keys' object is not subscriptable
```

Had to change in `lime_cpp.py:526-527` to use list() around idx_counts.values() :

```
               if (len(idx_counts) != 1 or list(idx_counts.values())[0] != 1
                        or list(idx_counts.keys())[0] != annot_indexes[sym_annot[rule.left]]):
``` 

Though I don't know python, and don't know if this is appropriate?

However, I now get a `calc.hpp` which compiles and works :+1:

**Comment by avakar** [comment]
Hi, yes, this was written long time ago when Python 2 was a thing. I guess I tried to update to Python 3 in the temp branch, but didn't catch all the places. I'm glad you got it to work!
